version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  lint: # this can be any name you choose
    resource_class: small
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run lint
          name: Run Linter
  build:
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $USERNAME
          password: $API_TOKEN
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push docker image
          command: | 
            docker build -t zsmith2171/webapp:latest "."
            docker push zsmith2171/webapp:latest
workflows:
  update_my_app:
    jobs:
      - lint
      - build:
          context: dockerhub
